[build]
  functions = "netlify/functions"
  
[functions]
  # Directory where Netlify Functions are stored
  directory = "netlify/functions"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200