[build]
  functions = "netlify/functions"

[functions]
  # Directory where Netlify Functions are stored
  directory = "netlify/functions"

  # Configure analyzeLayout function timeout
  [functions.analyzeLayout]
    # Netlify Pro tier supports up to 26 seconds for synchronous functions
    # Using Gemini 2.5 Flash with full 3-layout response
    timeout = 26  # 26 seconds (max for synchronous functions on Pro tier)