[build]
  functions = "netlify/functions"

[functions]
  # Directory where Netlify Functions are stored
  directory = "netlify/functions"

  # Configure analyzeLayout function timeout
  [functions.analyzeLayout]
    # Maximum timeout for free tier is 10 seconds
    # Using simplified prompt and fastest model to work within this limit
    timeout = 10  # 10 seconds (max for free tier)